version: "3"

volumes:
  zookeeper_storage:

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    environment:
      ZOO_MY_ID: 1

    ports:
      - 2181:2181
      
    volumes:
      - zookeeper_storage:/opt/zookeeper

