version: "3"

volumes:
  prometheus_storage:

networks:
  logging_network:
    external: true

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus

    networks:
      - logging_network

    ports:
      - 9090:9090
      
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_storage:/prometheus
