version: "3"

volumes:
  mongo_database:

networks: 
    mongo-compose-network:
      driver: bridge

services:
  mongo_db:
    container_name: mongo-server
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: yogen
      MONGO_INITDB_ROOT_PASSWORD: dat1234
    volumes:
      - mongo_database:/opt/database
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network


  mongo-express:
    container_name: mongo-express
    image: mongo-express
    links:
      - mongo_db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_MONGODB_ADMINUSERNAME: yogen
      ME_CONFIG_MONGODB_ADMINPASSWORD: dat1234
      ME_CONFIG_MONGODB_URL: mongodb://yogen:dat1234@mongo:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - mongo-compose-network