version: "3"

volumes:
  activemq_storage:

services:
  activemq:
    container_name: activemq
    image: apache/activemq-artemis:latest-alpine
    environment:
      - ARTEMIS_USER=yogen
      - ARTEMIS_PASSWORD=dat1234

    ports:
      - 61616:61616
      - 8161:8161
      
    volumes:
      - activemq_storage:/opt/message

