version: "3"

volumes:
  elastic_storage:
  logstash_storage:
  kibana_storage:

networks:
  elk_network:

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.14.3
    environment:
      ELASTIC_PASSWORD: yogen1234
      vm.max_map_count: 262144
      
    ports:
      - 9200:9200
      - 9300:9300

    networks:
      - elk_network
      
    volumes:
      - elastic_storage:/usr/share/elasticsearch/data

  logstash:
    container_name: logstash
    image: logstash:8.14.3


    networks:
      - elk_network

    volumes:
      - logstash_storage:/usr/share/logstash/
      # - ../../MIU/Courses/EA-Rene Dejong/Assignments/project/kube/logs/:/usr/share/data/:ro
      # - ./logstash.conf:/usr/share/logstash/config/

  
  kibana:
    container_name: kibana
    image: kibana:8.14.3
    ports:
      - 5601:5601
    networks:
      - elk_network
    volumes:
      - kibana_storage:/usr/share/kibana

